# Auto-generated by swaxs-beam-image (Scan mode). 913 points.
# Assumes the surrounding script already imports `bp` and defines `dets` and `piezo`.
from ophyd import Signal

def ezra_sample_scan(name = 'ezra_1'):
    # Auto-generated by swaxs-beam-image (Scan mode). 45467 points.
    from ophyd import Signal
    sample_signal = Signal(name='sample_name')
    dets = [pil2M,pil900KW,pin_diode, sample_name]

    # Per-run identifier — edit as needed; included in every event via the md template.

    yield from bp.grid_scan(
        dets,
        piezo.y, 7077.2760, 7377.2760, 151,   # outer (slow) axis
        piezo.x, -52619.7930, -52319.7930, 21,   # inner (fast) axis
        md={'sample_name': name+'_{sample_name}_x{piezo_x}_y{piezo_y}'},
    )

    yield from bp.grid_scan(
        dets,
        piezo.y, 7031.2420, 7331.2420, 151,   # outer (slow) axis
        piezo.x, -52505.7330, -51505.7330, 68,   # inner (fast) axis
        md={'sample_name': 'ezra_2_{sample_name}_x{piezo_x}_y{piezo_y}'},
    )

    yield from bp.grid_scan(
        dets,
        piezo.y, 7296.1070, 7596.1070, 151,   # outer (slow) axis
        piezo.x, -51332.5410, -50332.5410, 68,   # inner (fast) axis
        md={'sample_name': 'ezra_3_{sample_name}_x{piezo_x}_y{piezo_y}'},
    )


def ezra_1_grid_scan(name = 'ezra_1'):
    # Auto-generated by swaxs-beam-image (Scan mode)
    # grid scan over ezra_1 sample xxxx points
    dets = [pil2M,pil900KW,pin_diode]

    yield from bp.grid_scan(
        dets,
        piezo.y, 7077.2760, 7377.2760, 151,   # outer (slow) axis
        piezo.x, -52619.7930, -52319.7930, 21,   # inner (fast) axis
        md={'sample_name': name+'_x{piezo_x}_y{piezo_y}'}, # template for the filename is put in the start sample_name field
    )



def bookmark_scan():
    # Auto-generated by swaxs-beam-image (bookmark mode)
    # scan over xxxx samples chosen interactively vs on axis microscope
    from ophyd import Signal
    filename_signal = Signal(name='filename_template')
    dets = [pil2M,pil900KW,pin_diode,filename_signal]

    bookmark_names = {sample_1, sample_2, sample_3}
    xs =    {1,        2,        3,} # microns
    ys =    {4,        5,        6,} # microns
    zs =    {4,        4,        4,} # microns


    yield from bp.list_scan(
        dets,
        piezo.x, xs,
        piezo.y, ys,
        piezo.z, zs,
        filename_signal, bookmark_names,
        md={'sample_name': '{filename_template}'},# optionally add '_x{piezo_x}_y{piezo_y}' to add x and y positions to file name
    )



