# Auto-generated by swaxs-beam-image (Scan mode). 913 points.
# Assumes the surrounding script already imports `bp` and defines `dets` and `piezo`.
from ophyd import Signal

def ezra_sample_scan(name = 'ezra_1'):
    # === smi_plans note (REVIEW 2026-06-22) ================================
    # WHAT THIS DOES: micro-mapping — raster-scans a fine x-y grid over three sample areas,
    #   taking a SAXS+WAXS image at every point, with the x/y position written into each
    #   file name from the recorded data.
    #
    # 👍 NICE — this is already the modern style: one coordinated grid_scan per area, and
    #   the file name is templated from the recorded fields ({piezo_x}, {piezo_y}) rather
    #   than hand-built. smi_plans does exactly this kind of mapping, so the move is mostly
    #   a rename for tidiness and the extra metadata smi_plans records for you:
    #
    #     from smi_plans import map_grid_run, map_dets
    #     yield from map_grid_run(
    #         "ezra_1", map_dets(use_saxs=True, use_waxs=True),
    #         y=(7077.2760, 7377.2760, 151),     # outer (slow) axis, same numbers
    #         x=(-52619.7930, -52319.7930, 21))  # inner (fast) axis, same numbers
    #     # ...repeat for ezra_2 / ezra_3, or pass them as a map_bar of areas.
    #
    #   (Purely optional — this function works as-is; nothing here is broken.)
    # === end smi_plans note ================================================
    # Auto-generated by swaxs-beam-image (Scan mode). 45467 points.
    from ophyd import Signal
    sample_signal = Signal(name='sample_name')
    dets = [pil2M,pil900KW,pin_diode, sample_name]

    # Per-run identifier — edit as needed; included in every event via the md template.

    yield from bp.grid_scan(
        dets,
        piezo.y, 7077.2760, 7377.2760, 151,   # outer (slow) axis
        piezo.x, -52619.7930, -52319.7930, 21,   # inner (fast) axis
        md={'sample_name': name+'_{sample_name}_x{piezo_x}_y{piezo_y}'},
    )

    yield from bp.grid_scan(
        dets,
        piezo.y, 7031.2420, 7331.2420, 151,   # outer (slow) axis
        piezo.x, -52505.7330, -51505.7330, 68,   # inner (fast) axis
        md={'sample_name': 'ezra_2_{sample_name}_x{piezo_x}_y{piezo_y}'},
    )

    yield from bp.grid_scan(
        dets,
        piezo.y, 7296.1070, 7596.1070, 151,   # outer (slow) axis
        piezo.x, -51332.5410, -50332.5410, 68,   # inner (fast) axis
        md={'sample_name': 'ezra_3_{sample_name}_x{piezo_x}_y{piezo_y}'},
    )


def ezra_1_grid_scan(name = 'ezra_1'):
    # === smi_plans note (REVIEW 2026-06-22) ================================
    # WHAT THIS DOES: micro-mapping — a single fine x-y raster over the ezra_1 area, SAXS+
    #   WAXS image at each point, x/y written into the file name from recorded data.
    #
    # 👍 NICE — already the modern style (one grid_scan, templated file name). The smi_plans
    #   equivalent is one line and records a bit more metadata for you:
    #     from smi_plans import map_grid_run, map_dets
    #     yield from map_grid_run(
    #         "ezra_1", map_dets(use_saxs=True, use_waxs=True),
    #         y=(7077.2760, 7377.2760, 151), x=(-52619.7930, -52319.7930, 21))
    #   (Purely optional — this function works as-is; nothing here is broken.)
    # === end smi_plans note ================================================
    # Auto-generated by swaxs-beam-image (Scan mode)
    # grid scan over ezra_1 sample xxxx points
    dets = [pil2M,pil900KW,pin_diode]

    yield from bp.grid_scan(
        dets,
        piezo.y, 7077.2760, 7377.2760, 151,   # outer (slow) axis
        piezo.x, -52619.7930, -52319.7930, 21,   # inner (fast) axis
        md={'sample_name': name+'_x{piezo_x}_y{piezo_y}'}, # template for the filename is put in the start sample_name field
    )



def bookmark_scan():
    # === smi_plans note (REVIEW 2026-06-22) ================================
    # WHAT THIS DOES: micro-mapping at a handful of points you picked by eye on the on-axis
    #   microscope — visits each (x, y, z) bookmark and takes a SAXS+WAXS image, naming each
    #   file from its bookmark label.
    #
    # 👍 NICE — already the modern style: one coordinated list_scan and a templated file
    #   name from recorded fields. In smi_plans this is a list/line map over your chosen
    #   points:
    #     from smi_plans import map_line_run, map_dets, SampleList
    #     pts = SampleList.from_columns(name=["sample_1","sample_2","sample_3"],
    #                                   x=[1,2,3], y=[4,5,6], z=[4,4,4])
    #     yield from map_line_run("bookmarks", map_dets(use_saxs=True, use_waxs=True), pts)
    #   (Purely optional — this function works as-is; nothing here is broken. Heads-up: the
    #    bookmark lists use {curly braces}, which make Python *sets* (unordered) — for a
    #    repeatable order use [square brackets] / a SampleList as above.)
    # === end smi_plans note ================================================
    # Auto-generated by swaxs-beam-image (bookmark mode)
    # scan over xxxx samples chosen interactively vs on axis microscope
    from ophyd import Signal
    filename_signal = Signal(name='filename_template')
    dets = [pil2M,pil900KW,pin_diode,filename_signal]

    bookmark_names = {sample_1, sample_2, sample_3}
    xs =    {1,        2,        3,} # microns
    ys =    {4,        5,        6,} # microns
    zs =    {4,        4,        4,} # microns


    yield from bp.list_scan(
        dets,
        piezo.x, xs,
        piezo.y, ys,
        piezo.z, zs,
        filename_signal, bookmark_names,
        md={'sample_name': '{filename_template}'},# optionally add '_x{piezo_x}_y{piezo_y}' to add x and y positions to file name
    )



